config/routes.rb
Rails.application.routes.draw do
  resources :cages
  resources :dinosaurs
  resources :cage_searches
  resources :dinosaur_searches
  root to: "cages#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/cage_search.rb
class CageSearch < ApplicationRecord

    self.inheritance_column = "not_sti"

    def search_cages
        cage = Cage.all 

        cage = cage.where(['name LIKE ?', name]) if name.present?
        cage = cage.where(['power_status LIKE ?', power_status]) if power_status.present?

        return cage
    end 

end

app/controllers/cage_searches_controller.rb
class CageSearchesController < ApplicationController

    def show
        @cage_search = CageSearch.find(params[:id])
    end 

    def new 
        @cage_search = CageSearch.new
        @power_statuses = Cage.distinct.pluck(:power_status)
    end

    def create
        @cage_search = CageSearch.create(search_params)
        redirect_to @cage_search
    end 

    private

    def search_params
        params.require(:cage_search).permit(:name, :power_status)
    end 

end

app/helpers/cage_searches_helper.rb
module CageSearchesHelper
end

app/views/cage_searches/new.html.erb
<h1>Advanced Search</h1>

<%= form_with model: @cage_search do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :power_status %>
    <%= f.select :power_status, options_for_select(@power_statuses), include_blank: true %><br>

    <%= f.submit "Search" %>
<% end %>

<p><%= link_to "Back", '/cages' %></p>

app/views/cage_searches/show.html.erb
<h1>Search Results</h1>
<p><%= link_to "Back", new_cage_search_path %></p>

<% if @cage_search.search_cages.empty? %>
    <p>No Cages were found.</p>
<% else %>
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Max Capacity</th>
                <th>Number of Dinosaurs</th>
                <th colspan="3"></th>
            </tr>
        </thead>

        <tbody>
            <% @cage_search.search_cages.each do |cage| %>
            <tr>
                <td><%= cage.name %></td>
                <td><%= cage.power_status %></td>
                <td><%= cage.dinosaur_count %></td>
                <td><%= link_to 'Edit', edit_cage_path(cage) %></td>
                <td><%= link_to 'Delete', cage_path(cage), method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
            <% end %>
        </tbody>
</table>
<% end %>