config/routes.rb
Rails.application.routes.draw do
  resources :cages
  resources :dinosaurs
  resources :cage_searches
  resources :dinosaur_searches
  root to: "cages#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_header.html.erb
<section class="hero is-link is-small">
  <!-- Hero head: will stick at the top -->
  <div class="hero-head">
    <nav class="navbar" role="navigation" aria-label="main navigation">
      <div class="container">
        <div class="navbar-brand">
          <a class="navbar-item">
            <%= link_to root_path, class: "navbar-item" do %>
                <span class= "has-textweight-bold is-size-4 ml-4">Jurassic Park API</span>
            <% end %>
          </a>
          <span class="navbar-burger" data-target="navbarMenuHeroA">
            <span></span>
            <span></span>
            <span></span>
          </span>
        </div>
        <div id="navbarMenuHeroA" class="navbar-menu">
          <div class="navbar-end">
            <span class="navbar-item">
                <%= link_to "Create new cage", new_cage_path, class: "button is-success" %>
            <span class="navbar-item">
                <%= link_to "Create new dinosaur", new_dinosaur_path, class: "button is-warning" %>   
          </div>
        </div>
      </div>
    </nav>
  </div>

  <!-- Hero content: will be in the middle -->
  <div class="hero-body">
    <div class="container has-text-centered">
      <h1 class="title">
        <% if content_for(:title) %>
            <%= yield :title %>
        <% else %>
            Park Management System
        <% end %>
      </h1>
    
    </div>
  </div>

</section>