config/routes.rb
Rails.application.routes.draw do
  resources :cages
  resources :dinosaurs
  resources :cage_searches
  resources :dinosaur_searches
  root to: "cages#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/dinosaur_search.rb
class DinosaurSearch < ApplicationRecord

    self.inheritance_column = "not_sti"

    def search_dinosaurs
        dinosaur = Dinosaur.all 

        dinosaur = dinosaur.where(['name LIKE ?', name]) if name.present?
        dinosaur = dinosaur.where(['species LIKE ?', species]) if species.present?

        return dinosaur
    end 

end

app/controllers/dinosaur_searches_controller.rb
class DinosaurSearchesController < ApplicationController

    def show
        @dinosaur_search = DinosaurSearch.find(params[:id])
    end 

    def new 
        @dinosaur_search = DinosaurSearch.new
        @species = Dinosaur.distinct.pluck(:species)
    end

    def create
        @dinosaur_search = DinosaurSearch.create(search_params)
        redirect_to @dinosaur_search
    end 

    private

    def search_params
        params.require(:dinosaur_search).permit(:name, :species)
    end 

end

app/helpers/dinosaur_searches_helper.rb
module DinosaurSearchesHelper
end

app/views/dinosaur_searches/new.html.erb
<h1>Advanced Search</h1>

<%= form_with model: @dinosaur_search do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :species %>
    <%= f.select :species, options_for_select(@species), include_blank: true %><br>

    <%= f.submit "Search" %>
<% end %>

<p><%= link_to "Back", '/dinosaurs' %></p>

app/views/dinosaur_searches/show.html.erb
<h1>Search Results</h1>
<p><%= link_to "Back", new_dinosaur_search_path %></p>

<% if @dinosaur_search.search_dinosaurs.empty? %>
    <p>No Dinosaurs were found.</p>
<% else %>
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Species</th>
                <th>Diet_Type</th>
                <th colspan="3"></th>
            </tr>
        </thead>

        <tbody>
            <% @dinosaur_search.search_dinosaurs.each do |dinosaur| %>
            <tr>
                <td><%= dinosaur.name %></td>
                <td><%= dinosaur.species %></td>
                <td><%= dinosaur.diet_type %></td>
                <td><%= link_to 'Edit', edit_dinosaur_path(dinosaur) %></td>
                <td><%= link_to 'Delete', dinosaur_path(dinosaur), method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
            <% end %>
        </tbody>
</table>
<% end %>